name: iron build (EOL)

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]
  workflow_dispatch: 

jobs:
  iron_build:
    runs-on: ubuntu-22.04
    strategy:
        matrix:
          ros_distribution:
            - iron
    steps:
      - name: cancle preivious run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            ros-${{ matrix.ros_distribution }}-geometry-msgs \
            ros-${{ matrix.ros_distribution }}-tf2 \
            ros-${{ matrix.ros_distribution }}-tf2-ros \
            ros-${{ matrix.ros_distribution }}-ament-cmake \
            ros-${{ matrix.ros_distribution }}-ament-lint-auto \
            ros-${{ matrix.ros_distribution }}-ament-lint-common \
            ros-${{ matrix.ros_distribution }}-rclcpp \

      - name: Build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: mocap_nokov
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true
