name: noetic build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 
                            
jobs:
  noetic_build:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          ros_distribution:
            - noetic
    steps:
        - name: cancle preivious run
          uses: styfle/cancel-workflow-action@0.10.0
          with:
            access_token: ${{ github.token }}
        - name: Setup ROS environment
          uses: ros-tooling/setup-ros@v0.7
          with:
            required-ros-distributions: ${{ matrix.ros_distribution }}
        - name: Build and test ROS
          uses: ros-tooling/action-ros-ci@v0.4
          with:
            package-name: mocap_nokov
            target-ros1-distro: ${{ matrix.ros_distribution }}
            skip-tests: true

  